# Contains:
#   country2langs = {'us': 'en', 'brazil': 'pt', ... }
#   country_code2langs = {'US': 'en', ... }
#   country_name2langs = {'Czech Republic': 'cs', ... }

country2langs = {'ad': 'ca',
                 'ae': 'ar',
                 'af': 'fa, ps',
                 'afghanistan': 'fa, ps',
                 'ag': 'en',
                 'ai': 'en',
                 'al': 'sq',
                 'aland islands': 'sv',
                 'albania': 'sq',
                 'algeria': 'ar',
                 'am': 'hy',
                 'american samoa': 'en, sm',
                 'andorra': 'ca',
                 'angola': 'pt',
                 'anguilla': 'en',
                 'antarctica': 'en, es, fr, ru',
                 'antigua and barbuda': 'en',
                 'ao': 'pt',
                 'aq': 'en, es, fr, ru',
                 'ar': 'es',
                 'argentina': 'es',
                 'armenia': 'hy',
                 'aruba': 'nl, pa',
                 'as': 'en, sm',
                 'at': 'de',
                 'au': 'en',
                 'australia': 'en',
                 'austria': 'de',
                 'aw': 'nl, pa',
                 'ax': 'sv',
                 'az': 'az',
                 'azerbaijan': 'az',
                 'ba': 'bs, hr, sr',
                 'bahamas': 'en',
                 'bahrein': 'ar',
                 'bangladesh': 'bn',
                 'barbados': 'en',
                 'bb': 'en',
                 'bd': 'bn',
                 'be': 'nl, fr, de',
                 'belarus': 'be, ru',
                 'belgium': 'nl, fr, de',
                 'belize': 'en',
                 'benin': 'fr',
                 'bermuda': 'en',
                 'bf': 'fr',
                 'bg': 'bg',
                 'bh': 'ar',
                 'bhutan': 'dz',
                 'bi': 'fr',
                 'bj': 'fr',
                 'bl': 'fr',
                 'bm': 'en',
                 'bn': 'ms',
                 'bo': 'es, qu, gn, ay',
                 'bolivia': 'es, qu, gn, ay',
                 'bosnia and herzegovina': 'bs, hr, sr',
                 'botswana': 'en, tn',
                 'bouvet island': 'no',
                 'bq': 'nl',
                 'br': 'pt',
                 'brazil': 'pt',
                 'british indian ocean territory': 'en',
                 'british virgin islands': 'en',
                 'brunei darussalam': 'ms',
                 'bs': 'en',
                 'bt': 'dz',
                 'bulgaria': 'bg',
                 'burkina faso': 'fr',
                 'burundi': 'fr',
                 'bv': 'no',
                 'bw': 'en, tn',
                 'by': 'be, ru',
                 'bz': 'en',
                 'ca': 'en, fr',
                 'cabo verde': 'pt',
                 'cambodia': 'km',
                 'cameroon': 'fr, en',
                 'canada': 'en, fr',
                 'caribbean netherlands': 'nl',
                 'cayman islands': 'en',
                 'cc': 'en',
                 'cd': 'fr',
                 'centrafrican republic': 'fr, sg',
                 'cf': 'fr, sg',
                 'cg': 'fr',
                 'ch': 'de, fr, it, rm',
                 'chad': 'fr, ar',
                 'chile': 'es',
                 'china': 'zh',
                 'christmas island': 'en',
                 'ci': 'fr',
                 'city of the vatican': 'it',
                 'ck': 'en, ra',
                 'cl': 'es',
                 'cm': 'fr, en',
                 'cn': 'zh',
                 'co': 'es',
                 'cocos (keeling) islands': 'en',
                 'colombia': 'es',
                 'comores': 'ar, fr, sw',
                 "cook i'slands": 'en, ra',
                 'costa rica': 'es',
                 'cr': 'es',
                 'croatia': 'hr',
                 'cu': 'es',
                 'cuba': 'es',
                 'curaçao': 'nl, en',
                 'cv': 'pt',
                 'cw': 'nl, en',
                 'cx': 'en',
                 'cy': 'el, tr',
                 'cyprus': 'el, tr',
                 'cz': 'cs',
                 'czech republic': 'cs',
                 'côte divoire': 'fr',
                 'de': 'de',
                 'democratic republic of the congo (congo-kinshasa, former zaire)': 'fr',
                 'denmark': 'da',
                 'dj': 'fr, ar, so, aa',
                 'djibouti': 'fr, ar, so, aa',
                 'dk': 'da',
                 'dm': 'en',
                 'do': 'es',
                 'dominica': 'en',
                 'dominican republic': 'es',
                 'dz': 'ar',
                 'ec': 'es',
                 'ecuador': 'es',
                 'ee': 'et',
                 'eg': 'ar',
                 'egypt': 'ar',
                 'eh': 'ar, es, fr',
                 'el salvador': 'es',
                 'equatorial guinea': 'es, fr, pt',
                 'er': 'ti, ar, en',
                 'eritrea': 'ti, ar, en',
                 'es': 'as',
                 'estonia': 'et',
                 'et': 'am, om',
                 'ethiopia': 'am, om',
                 'falkland islands': 'en',
                 'faroe islands': 'fo, da',
                 'fi': 'fi, sv, se',
                 'fiji': 'en',
                 'finland': 'fi, sv, se',
                 'fj': 'en',
                 'fk': 'en',
                 'fm': 'en',
                 'fo': 'fo, da',
                 'fr': 'fr',
                 'france': 'fr',
                 'french guiana': 'fr',
                 'french polynesia': 'fr',
                 'french southern and antarctic lands': 'fr',
                 'ga': 'fr',
                 'gabon': 'fr',
                 'gb': 'en, ga, cy, gd, kw',
                 'gd': 'en',
                 'ge': 'ka',
                 'georgia': 'ka',
                 'germany': 'de',
                 'gf': 'fr',
                 'gg': 'en',
                 'gh': 'en',
                 'ghana': 'en',
                 'gi': 'en',
                 'gibraltar': 'en',
                 'gl': 'kl, da',
                 'gm': 'en',
                 'gn': 'fr',
                 'gp': 'fr',
                 'gq': 'es, fr, pt',
                 'gr': 'el',
                 'greece': 'el',
                 'greenland': 'kl, da',
                 'grenada': 'en',
                 'gs': 'en',
                 'gt': 'es',
                 'gu': 'en, ch',
                 'guadeloupe': 'fr',
                 'guam': 'en, ch',
                 'guatemala': 'es',
                 'guernsey': 'en',
                 'guinea': 'fr',
                 'guinea bissau': 'pt',
                 'guyana': 'en',
                 'gw': 'pt',
                 'gy': 'en',
                 'haiti': 'fr, ht',
                 'heard island and mcdonald islands': 'en',
                 'hk': 'zh',
                 'hm': 'en',
                 'hn': 'es',
                 'honduras': 'es',
                 'hong kong (sar of china)': 'zh',
                 'hr': 'hr',
                 'ht': 'fr, ht',
                 'hu': 'hu',
                 'hungary': 'hu',
                 'iceland': 'is',
                 'id': 'id',
                 'ie': 'en, ga',
                 'il': 'he',
                 'im': 'en',
                 'in': 'hi, en',
                 'india': 'hi, en',
                 'indonesia': 'id',
                 'io': 'en',
                 'iq': 'ar, ku',
                 'ir': 'fa',
                 'iran': 'fa',
                 'iraq': 'ar, ku',
                 'ireland': 'en, ga',
                 'is': 'is',
                 'isle of man': 'en',
                 'israel': 'he',
                 'it': 'it, de, fr',
                 'italy': 'it, de, fr',
                 'jamaica': 'en',
                 'japan': 'ja',
                 'je': 'en',
                 'jersey': 'en',
                 'jm': 'en',
                 'jo': 'ar',
                 'jordan': 'ar',
                 'jp': 'ja',
                 'kazakhstan': 'kk, ru',
                 'ke': 'sw, en',
                 'kenya': 'sw, en',
                 'kg': 'ky, ru',
                 'kh': 'km',
                 'ki': 'en',
                 'kiribati': 'en',
                 'km': 'ar, fr, sw',
                 'kn': 'en',
                 'kp': 'ko',
                 'kr': 'ko, en',
                 'kuweit': 'ar',
                 'kw': 'ar',
                 'ky': 'en',
                 'kyrgyzstan': 'ky, ru',
                 'kz': 'kk, ru',
                 'la': 'lo',
                 'laos': 'lo',
                 'latvia': 'lv',
                 'lb': 'ar, fr',
                 'lc': 'en',
                 'lebanon': 'ar, fr',
                 'lesotho': 'en, st',
                 'li': 'de',
                 'liberia': 'en',
                 'libya': 'ar',
                 'liechtenstein': 'de',
                 'lithuania': 'lt',
                 'lk': 'si, ta',
                 'lr': 'en',
                 'ls': 'en, st',
                 'lt': 'lt',
                 'lu': 'lb, fr, de',
                 'luxembourg': 'lb, fr, de',
                 'lv': 'lv',
                 'ly': 'ar',
                 'ma': 'fr, zg',
                 'macao (sar of china)': 'zh',
                 'macedonia (former yugoslav republic of)': 'mk',
                 'madagascar': 'mg, fr',
                 'malawi': 'en, ny',
                 'malaysia': 'ms',
                 'maldives': 'dv',
                 'mali': 'fr',
                 'malta': 'mt, en',
                 'marshall islands': 'en, mh',
                 'martinique': 'fr',
                 'mauritania': 'ar, fr',
                 'mauritius': 'mf',
                 'mayotte': 'fr',
                 'mc': 'fr',
                 'md': 'ro, ru, uk',
                 'me': 'sr',
                 'mexico': 'es',
                 'mf': 'fr',
                 'mg': 'mg, fr',
                 'mh': 'en, mh',
                 'micronesia (federated states of)': 'en',
                 'mk': 'mk',
                 'ml': 'fr',
                 'mm': 'my',
                 'mn': 'mn',
                 'mo': 'zh',
                 'moldova': 'ro, ru, uk',
                 'monaco': 'fr',
                 'mongolia': 'mn',
                 'montenegro': 'sr',
                 'montserrat': 'en',
                 'morocco': 'fr, zg',
                 'mozambique': 'pt',
                 'mp': 'en, ch',
                 'mq': 'fr',
                 'mr': 'ar, fr',
                 'ms': 'en',
                 'mt': 'mt, en',
                 'mu': 'mf',
                 'mv': 'dv',
                 'mw': 'en, ny',
                 'mx': 'es',
                 'my': 'ms',
                 'myanmar': 'my',
                 'mz': 'pt',
                 'na': 'en, sf, de',
                 'namibia': 'en, sf, de',
                 'nauru': 'na, en',
                 'nc': 'fr',
                 'ne': 'fr',
                 'nepal': 'ne',
                 'new caledonia': 'fr',
                 'new zealand': 'mi, en',
                 'nf': 'en, pi',
                 'ng': 'en',
                 'ni': 'es',
                 'nicaragua': 'es',
                 'niger': 'fr',
                 'nigeria': 'en',
                 'niue': 'ni',
                 'nl': 'nl',
                 'no': 'nb, nn, no, se',
                 'norfolk island': 'en, pi',
                 'north korea': 'ko',
                 'northern mariana islands': 'en, ch',
                 'norway': 'nb, nn, no, se',
                 'np': 'ne',
                 'nr': 'na, en',
                 'nu': 'ni',
                 'nz': 'mi, en',
                 'om': 'ar',
                 'oman': 'ar',
                 'pa': 'es',
                 'pakistan': 'en, ur',
                 'palau': 'en, pa',
                 'palestinian territory': 'ar, he',
                 'panama': 'es',
                 'papua new guinea': 'en, tp',
                 'paraguay': 'es, gn',
                 'pe': 'es',
                 'peru': 'es',
                 'pf': 'fr',
                 'pg': 'en, tp',
                 'ph': 'en, tl',
                 'philippines': 'en, tl',
                 'pitcairn': 'en, pi',
                 'pk': 'en, ur',
                 'pl': 'pl',
                 'pm': 'fr',
                 'pn': 'en, pi',
                 'poland': 'pl',
                 'portugal': 'pt',
                 'pr': 'es, en',
                 'ps': 'ar, he',
                 'pt': 'pt',
                 'puerto rico': 'es, en',
                 'pw': 'en, pa',
                 'py': 'es, gn',
                 'qa': 'ar',
                 'qatar': 'ar',
                 're': 'fr',
                 'republic of the congo (congo-brazzaville)': 'fr',
                 'reunion': 'fr',
                 'ro': 'ro',
                 'romania': 'ro',
                 'rs': 'sr, sr',
                 'ru': 'ru',
                 'russia': 'ru',
                 'rw': 'rw, fr, en',
                 'rwanda': 'rw, fr, en',
                 'sa': 'ar',
                 'saint helena': 'en',
                 'saint kitts and nevis': 'en',
                 'saint lucia': 'en',
                 'saint martin (dutch part)': 'nl, en',
                 'saint martin (french part)': 'fr',
                 'saint pierre and miquelon': 'fr',
                 'saint vincent and the grenadines': 'en',
                 'saint-barthélemy': 'fr',
                 'samoa': 'sm, en',
                 'san marino': 'it',
                 'saudi arabia': 'ar',
                 'sb': 'en',
                 'sc': 'fr, en, cr',
                 'sd': 'ar, en',
                 'se': 'sv',
                 'serbia': 'sr, sr',
                 'seychelles': 'fr, en, cr',
                 'sg': 'zh',
                 'sh': 'en',
                 'si': 'sl',
                 'sierra leone': 'en',
                 'singapore': 'zh',
                 'sj': 'no',
                 'sk': 'sk',
                 'sl': 'en',
                 'slovakia': 'sk',
                 'slovenia': 'sl',
                 'sm': 'it',
                 'sn': 'fr',
                 'so': 'so, ar',
                 'solomon islands': 'en',
                 'somalia': 'so, ar',
                 'south africa': 'en, af, st, tn, xh, zu',
                 'south georgia and the south sandwich islands': 'en',
                 'south korea': 'ko, en',
                 'south sudan': 'en',
                 'spain': 'as',
                 'sr': 'nl',
                 'sri lanka': 'si, ta',
                 'ss': 'en',
                 'st': 'pt',
                 'sudan': 'ar, en',
                 'suriname': 'nl',
                 'sv': 'es',
                 'svalbard and jan mayen': 'no',
                 'swaziland': 'en, ss',
                 'sweden': 'sv',
                 'switzerland': 'de, fr, it, rm',
                 'sx': 'nl, en',
                 'sy': 'ar',
                 'syria': 'ar',
                 'sz': 'en, ss',
                 'são tomé and príncipe': 'pt',
                 'sénégal': 'fr',
                 'taiwan': 'zh',
                 'tajikistan': 'tg, ru',
                 'tanzania': 'sw, en',
                 'tc': 'en',
                 'td': 'fr, ar',
                 'tf': 'fr',
                 'tg': 'fr',
                 'th': 'th',
                 'thailand': 'th',
                 'the gambia': 'en',
                 'the netherlands': 'nl',
                 'timor-leste': 'pt, te',
                 'tj': 'tg, ru',
                 'tk': 'tk',
                 'tl': 'pt, te',
                 'tm': 'tk',
                 'tn': 'ar, fr',
                 'to': 'en',
                 'togo': 'fr',
                 'tokelau': 'tk',
                 'tonga': 'en',
                 'tr': 'tr',
                 'trinidad and tobago': 'en',
                 'tt': 'en',
                 'tunisia': 'ar, fr',
                 'turkey': 'tr',
                 'turkmenistan': 'tk',
                 'turks and caicos islands': 'en',
                 'tuvalu': 'en',
                 'tv': 'en',
                 'tw': 'zh',
                 'tz': 'sw, en',
                 'ua': 'uk',
                 'ug': 'en, sw',
                 'uganda': 'en, sw',
                 'ukraine': 'uk',
                 'um': 'en',
                 'united arab emirates': 'ar',
                 'united kingdom': 'en, ga, cy, gd, kw',
                 'united states minor outlying islands': 'en',
                 'united states of america': 'en',
                 'united states virgin islands': 'en',
                 'uruguay': 'es',
                 'us': 'en',
                 'uy': 'es',
                 'uz': 'uz, ka',
                 'uzbekistan': 'uz, ka',
                 'va': 'it',
                 'vanuatu': 'bi, en, fr',
                 'vc': 'en',
                 've': 'es',
                 'venezuela': 'es',
                 'vg': 'en',
                 'vi': 'en',
                 'vietnam': 'vi',
                 'vn': 'vi',
                 'vu': 'bi, en, fr',
                 'wallis and futuna': 'fr',
                 'western sahara': 'ar, es, fr',
                 'wf': 'fr',
                 'ws': 'sm, en',
                 'ye': 'ar',
                 'yemen': 'ar',
                 'yt': 'fr',
                 'za': 'en, af, st, tn, xh, zu',
                 'zambia': 'en',
                 'zimbabwe': 'en, sn, nd',
                 'zm': 'en',
                 'zw': 'en, sn, nd'}

country_code2langs = {
    'AD': 'ca',
    'AE': 'ar',
    'AF': 'fa, ps',
    'AG': 'en',
    'AI': 'en',
    'AL': 'sq',
    'AM': 'hy',
    'AO': 'pt',
    'AQ': 'en, es, fr, ru',
    'AR': 'es',
    'AS': 'en, sm',
    'AT': 'de',
    'AU': 'en',
    'AW': 'nl, pa',
    'AX': 'sv',
    'AZ': 'az',
    'BA': 'bs, hr, sr',
    'BB': 'en',
    'BD': 'bn',
    'BE': 'nl, fr, de',
    'BF': 'fr',
    'BG': 'bg',
    'BH': 'ar',
    'BI': 'fr',
    'BJ': 'fr',
    'BL': 'fr',
    'BM': 'en',
    'BN': 'ms',
    'BO': 'es, qu, gn, ay',
    'BQ': 'nl',
    'BR': 'pt',
    'BS': 'en',
    'BT': 'dz',
    'BV': 'no',
    'BW': 'en, tn',
    'BY': 'be, ru',
    'BZ': 'en',
    'CA': 'en, fr',
    'CC': 'en',
    'CD': 'fr',
    'CF': 'fr, sg',
    'CG': 'fr',
    'CH': 'de, fr, it, rm',
    'CI': 'fr',
    'CK': 'en, ra',
    'CL': 'es',
    'CM': 'fr, en',
    'CN': 'zh',
    'CO': 'es',
    'CR': 'es',
    'CU': 'es',
    'CV': 'pt',
    'CW': 'nl, en',
    'CX': 'en',
    'CY': 'el, tr',
    'CZ': 'cs',
    'DE': 'de',
    'DJ': 'fr, ar, so, aa',
    'DK': 'da',
    'DM': 'en',
    'DO': 'es',
    'DZ': 'ar',
    'EC': 'es',
    'EE': 'et',
    'EG': 'ar',
    'EH': 'ar, es, fr',
    'ER': 'ti, ar, en',
    'ES': 'as',
    'ET': 'am, om',
    'FI': 'fi, sv, se',
    'FJ': 'en',
    'FK': 'en',
    'FM': 'en',
    'FO': 'fo, da',
    'FR': 'fr',
    'GA': 'fr',
    'GB': 'en, ga, cy, gd, kw',
    'GD': 'en',
    'GE': 'ka',
    'GF': 'fr',
    'GG': 'en',
    'GH': 'en',
    'GI': 'en',
    'GL': 'kl, da',
    'GM': 'en',
    'GN': 'fr',
    'GP': 'fr',
    'GQ': 'es, fr, pt',
    'GR': 'el',
    'GS': 'en',
    'GT': 'es',
    'GU': 'en, ch',
    'GW': 'pt',
    'GY': 'en',
    'HK': 'zh',
    'HM': 'en',
    'HN': 'es',
    'HR': 'hr',
    'HT': 'fr, ht',
    'HU': 'hu',
    'ID': 'id',
    'IE': 'en, ga',
    'IL': 'he',
    'IM': 'en',
    'IN': 'hi, en',
    'IO': 'en',
    'IQ': 'ar, ku',
    'IR': 'fa',
    'IS': 'is',
    'IT': 'it, de, fr',
    'JE': 'en',
    'JM': 'en',
    'JO': 'ar',
    'JP': 'ja',
    'KE': 'sw, en',
    'KG': 'ky, ru',
    'KH': 'km',
    'KI': 'en',
    'KM': 'ar, fr, sw',
    'KN': 'en',
    'KP': 'ko',
    'KR': 'ko, en',
    'KW': 'ar',
    'KY': 'en',
    'KZ': 'kk, ru',
    'LA': 'lo',
    'LB': 'ar, fr',
    'LC': 'en',
    'LI': 'de',
    'LK': 'si, ta',
    'LR': 'en',
    'LS': 'en, st',
    'LT': 'lt',
    'LU': 'lb, fr, de',
    'LV': 'lv',
    'LY': 'ar',
    'MA': 'fr, zg',
    'MC': 'fr',
    'MD': 'ro, ru, uk',
    'ME': 'sr',
    'MF': 'fr',
    'MG': 'mg, fr',
    'MH': 'en, mh',
    'MK': 'mk',
    'ML': 'fr',
    'MM': 'my',
    'MN': 'mn',
    'MO': 'zh',
    'MP': 'en, ch',
    'MQ': 'fr',
    'MR': 'ar, fr',
    'MS': 'en',
    'MT': 'mt, en',
    'MU': 'mf',
    'MV': 'dv',
    'MW': 'en, ny',
    'MX': 'es',
    'MY': 'ms',
    'MZ': 'pt',
    'NA': 'en, sf, de',
    'NC': 'fr',
    'NE': 'fr',
    'NF': 'en, pi',
    'NG': 'en',
    'NI': 'es',
    'NL': 'nl',
    'NO': 'nb, nn, no, se',
    'NP': 'ne',
    'NR': 'na, en',
    'NU': 'ni',
    'NZ': 'mi, en',
    'OM': 'ar',
    'PA': 'es',
    'PE': 'es',
    'PF': 'fr',
    'PG': 'en, tp',
    'PH': 'en, tl',
    'PK': 'en, ur',
    'PL': 'pl',
    'PM': 'fr',
    'PN': 'en, pi',
    'PR': 'es, en',
    'PS': 'ar, he',
    'PT': 'pt',
    'PW': 'en, pa',
    'PY': 'es, gn',
    'QA': 'ar',
    'RE': 'fr',
    'RO': 'ro',
    'RS': 'sr, sr',
    'RU': 'ru',
    'RW': 'rw, fr, en',
    'SA': 'ar',
    'SB': 'en',
    'SC': 'fr, en, cr',
    'SD': 'ar, en',
    'SE': 'sv',
    'SG': 'zh',
    'SH': 'en',
    'SI': 'sl',
    'SJ': 'no',
    'SK': 'sk',
    'SL': 'en',
    'SM': 'it',
    'SN': 'fr',
    'SO': 'so, ar',
    'SR': 'nl',
    'ST': 'pt',
    'SS': 'en',
    'SV': 'es',
    'SX': 'nl, en',
    'SY': 'ar',
    'SZ': 'en, ss',
    'TC': 'en',
    'TD': 'fr, ar',
    'TF': 'fr',
    'TG': 'fr',
    'TH': 'th',
    'TJ': 'tg, ru',
    'TK': 'tk',
    'TL': 'pt, te',
    'TM': 'tk',
    'TN': 'ar, fr',
    'TO': 'en',
    'TR': 'tr',
    'TT': 'en',
    'TV': 'en',
    'TW': 'zh',
    'TZ': 'sw, en',
    'UA': 'uk',
    'UG': 'en, sw',
    'UM': 'en',
    'US': 'en',
    'UY': 'es',
    'UZ': 'uz, ka',
    'VA': 'it',
    'VC': 'en',
    'VE': 'es',
    'VG': 'en',
    'VI': 'en',
    'VN': 'vi',
    'VU': 'bi, en, fr',
    'WF': 'fr',
    'WS': 'sm, en',
    'YE': 'ar',
    'YT': 'fr',
    'ZA': 'en, af, st, tn, xh, zu',
    'ZM': 'en',
    'ZW': 'en, sn, nd',
    'ca': 'ca',
    'sq': 'sq',
    'hy': 'hy',
    'az': 'az',
    'bs': 'bs',
    'bn': 'bn',
    'bg': 'bg',
    'dz': 'dz',
    'be': 'be',
    'cs': 'cs',
    'da': 'da',
    'et': 'et',
    'ti': 'ti',
    'as': 'as',
    'am': 'am',
    'fi': 'fi',
    'fo': 'fo',
    'ka': 'ka',
    'kl': 'kl',
    'el': 'el',
    'hr': 'hr',
    'hu': 'hu',
    'id': 'id',
    'he': 'he',
    'hi': 'hi',
    'fa': 'fa',
    'is': 'is',
    'ja': 'ja',
    'ky': 'ky',
    'km': 'km',
    'ko': 'ko',
    'kk': 'kk',
    'lo': 'lo',
    'de': 'de',
    'si': 'si',
    'lt': 'lt',
    'lb': 'lb',
    'lv': 'lv',
    'mg': 'mg',
    'mk': 'mk',
    'my': 'my',
    'mn': 'mn',
    'mt': 'mt',
    'mf': 'mf',
    'dv': 'dv',
    'ms': 'ms',
    'nb': 'nb',
    'ne': 'ne',
    'na': 'na',
    'ni': 'ni',
    'mi': 'mi',
    'pl': 'pl',
    'ro': 'ro',
    'sr': 'sr',
    'ru': 'ru',
    'rw': 'rw',
    'sv': 'sv',
    'sl': 'sl',
    'no': 'no',
    'sk': 'sk',
    'so': 'so',
    'nl': 'nl',
    'th': 'th',
    'tg': 'tg',
    'pt': 'pt',
    'tk': 'tk',
    'tr': 'tr',
    'zh': 'zh',
    'sw': 'sw',
    'uk': 'uk',
    'uz': 'uz',
    'it': 'it',
    'es': 'es',
    'vi': 'vi',
    'bi': 'bi',
    'sm': 'sm',
    'ar': 'ar',
    'fr': 'fr',
    'en': 'en',
}
country_name2langs = {
    'Andorra': 'ca',
    'United Arab Emirates': 'ar',
    'Afghanistan': 'fa, ps',
    'Antigua and Barbuda': 'en',
    'Anguilla': 'en',
    'Albania': 'sq',
    'Armenia': 'hy',
    'Angola': 'pt',
    'Antarctica': 'en, es, fr, ru',
    'Argentina': 'es',
    'American Samoa': 'en, sm',
    'Austria': 'de',
    'Australia': 'en',
    'Aruba': 'nl, pa',
    'Aland Islands': 'sv',
    'Azerbaijan': 'az',
    'Bosnia and Herzegovina': 'bs, hr, sr',
    'Barbados': 'en',
    'Bangladesh': 'bn',
    'Belgium': 'nl, fr, de',
    'Burkina Faso': 'fr',
    'Bulgaria': 'bg',
    'Bahrein': 'ar',
    'Burundi': 'fr',
    'Benin': 'fr',
    'Saint-Barthélemy': 'fr',
    'Bermuda': 'en',
    'Brunei Darussalam': 'ms',
    'Bolivia': 'es, qu, gn, ay',
    'Caribbean Netherlands': 'nl',
    'Brazil': 'pt',
    'Bahamas': 'en',
    'Bhutan': 'dz',
    'Bouvet Island': 'no',
    'Botswana': 'en, tn',
    'Belarus': 'be, ru',
    'Belize': 'en',
    'Canada': 'en, fr',
    'Cocos (Keeling) Islands': 'en',
    'Democratic Republic of the Congo (Congo-Kinshasa, former Zaire)': 'fr',
    'Centrafrican Republic': 'fr, sg',
    'Republic of the Congo (Congo-Brazzaville)': 'fr',
    'Switzerland': 'de, fr, it, rm',
    'Côte dIvoire': 'fr',
    'Cook I\'slands': 'en, ra',
    'Chile': 'es',
    'Cameroon': 'fr, en',
    'China': 'zh',
    'Colombia': 'es',
    'Costa Rica': 'es',
    'Cuba': 'es',
    'Cabo Verde': 'pt',
    'Curaçao': 'nl, en',
    'Christmas Island': 'en',
    'Cyprus': 'el, tr',
    'Czech Republic': 'cs',
    'Germany': 'de',
    'Djibouti': 'fr, ar, so, aa',
    'Denmark': 'da',
    'Dominica': 'en',
    'Dominican Republic': 'es',
    'Algeria': 'ar',
    'Ecuador': 'es',
    'Estonia': 'et',
    'Egypt': 'ar',
    'Western Sahara': 'ar, es, fr',
    'Eritrea': 'ti, ar, en',
    'Spain': 'as',
    'Ethiopia': 'am, om',
    'Finland': 'fi, sv, se',
    'Fiji': 'en',
    'Falkland Islands': 'en',
    'Micronesia (Federated States of)': 'en',
    'Faroe Islands': 'fo, da',
    'France': 'fr',
    'Gabon': 'fr',
    'United Kingdom': 'en, ga, cy, gd, kw',
    'Grenada': 'en',
    'Georgia': 'ka',
    'French Guiana': 'fr',
    'Guernsey': 'en',
    'Ghana': 'en',
    'Gibraltar': 'en',
    'Greenland': 'kl, da',
    'The Gambia': 'en',
    'Guinea': 'fr',
    'Guadeloupe': 'fr',
    'Equatorial Guinea': 'es, fr, pt',
    'Greece': 'el',
    'South Georgia and the South Sandwich Islands': 'en',
    'Guatemala': 'es',
    'Guam': 'en, ch',
    'Guinea Bissau': 'pt',
    'Guyana': 'en',
    'Hong Kong (SAR of China)': 'zh',
    'Heard Island and McDonald Islands': 'en',
    'Honduras': 'es',
    'Croatia': 'hr',
    'Haiti': 'fr, ht',
    'Hungary': 'hu',
    'Indonesia': 'id',
    'Ireland': 'en, ga',
    'Israel': 'he',
    'Isle of Man': 'en',
    'India': 'hi, en',
    'British Indian Ocean Territory': 'en',
    'Iraq': 'ar, ku',
    'Iran': 'fa',
    'Iceland': 'is',
    'Italy': 'it, de, fr',
    'Jersey': 'en',
    'Jamaica': 'en',
    'Jordan': 'ar',
    'Japan': 'ja',
    'Kenya': 'sw, en',
    'Kyrgyzstan': 'ky, ru',
    'Cambodia': 'km',
    'Kiribati': 'en',
    'Comores': 'ar, fr, sw',
    'Saint Kitts and Nevis': 'en',
    'North Korea': 'ko',
    'South Korea': 'ko, en',
    'Kuweit': 'ar',
    'Cayman Islands': 'en',
    'Kazakhstan': 'kk, ru',
    'Laos': 'lo',
    'Lebanon': 'ar, fr',
    'Saint Lucia': 'en',
    'Liechtenstein': 'de',
    'Sri Lanka': 'si, ta',
    'Liberia': 'en',
    'Lesotho': 'en, st',
    'Lithuania': 'lt',
    'Luxembourg': 'lb, fr, de',
    'Latvia': 'lv',
    'Libya': 'ar',
    'Morocco': 'fr, zg',
    'Monaco': 'fr',
    'Moldova': 'ro, ru, uk',
    'Montenegro': 'sr',
    'Saint Martin (French part)': 'fr',
    'Madagascar': 'mg, fr',
    'Marshall Islands': 'en, mh',
    'Macedonia (Former Yugoslav Republic of)': 'mk',
    'Mali': 'fr',
    'Myanmar': 'my',
    'Mongolia': 'mn',
    'Macao (SAR of China)': 'zh',
    'Northern Mariana Islands': 'en, ch',
    'Martinique': 'fr',
    'Mauritania': 'ar, fr',
    'Montserrat': 'en',
    'Malta': 'mt, en',
    'Mauritius': 'mf',
    'Maldives': 'dv',
    'Malawi': 'en, ny',
    'Mexico': 'es',
    'Malaysia': 'ms',
    'Mozambique': 'pt',
    'Namibia': 'en, sf, de',
    'New Caledonia': 'fr',
    'Niger': 'fr',
    'Norfolk Island': 'en, pi',
    'Nigeria': 'en',
    'Nicaragua': 'es',
    'The Netherlands': 'nl',
    'Norway': 'nb, nn, no, se',
    'Nepal': 'ne',
    'Nauru': 'na, en',
    'Niue': 'ni',
    'New Zealand': 'mi, en',
    'Oman': 'ar',
    'Panama': 'es',
    'Peru': 'es',
    'French Polynesia': 'fr',
    'Papua New Guinea': 'en, tp',
    'Philippines': 'en, tl',
    'Pakistan': 'en, ur',
    'Poland': 'pl',
    'Saint Pierre and Miquelon': 'fr',
    'Pitcairn': 'en, pi',
    'Puerto Rico': 'es, en',
    'Palestinian Territory': 'ar, he',
    'Portugal': 'pt',
    'Palau': 'en, pa',
    'Paraguay': 'es, gn',
    'Qatar': 'ar',
    'Reunion': 'fr',
    'Romania': 'ro',
    'Serbia': 'sr, sr',
    'Russia': 'ru',
    'Rwanda': 'rw, fr, en',
    'Saudi Arabia': 'ar',
    'Solomon Islands': 'en',
    'Seychelles': 'fr, en, cr',
    'Sudan': 'ar, en',
    'Sweden': 'sv',
    'Singapore': 'zh',
    'Saint Helena': 'en',
    'Slovenia': 'sl',
    'Svalbard and Jan Mayen': 'no',
    'Slovakia': 'sk',
    'Sierra Leone': 'en',
    'San Marino': 'it',
    'Sénégal': 'fr',
    'Somalia': 'so, ar',
    'Suriname': 'nl',
    'São Tomé and Príncipe': 'pt',
    'South Sudan': 'en',
    'El Salvador': 'es',
    'Saint Martin (Dutch part)': 'nl, en',
    'Syria': 'ar',
    'Swaziland': 'en, ss',
    'Turks and Caicos Islands': 'en',
    'Chad': 'fr, ar',
    'French Southern and Antarctic Lands': 'fr',
    'Togo': 'fr',
    'Thailand': 'th',
    'Tajikistan': 'tg, ru',
    'Tokelau': 'tk',
    'Timor-Leste': 'pt, te',
    'Turkmenistan': 'tk',
    'Tunisia': 'ar, fr',
    'Tonga': 'en',
    'Turkey': 'tr',
    'Trinidad and Tobago': 'en',
    'Tuvalu': 'en',
    'Taiwan': 'zh',
    'Tanzania': 'sw, en',
    'Ukraine': 'uk',
    'Uganda': 'en, sw',
    'United States Minor Outlying Islands': 'en',
    'United States of America': 'en',
    'Uruguay': 'es',
    'Uzbekistan': 'uz, ka',
    'City of the Vatican': 'it',
    'Saint Vincent and the Grenadines': 'en',
    'Venezuela': 'es',
    'British Virgin Islands': 'en',
    'United States Virgin Islands': 'en',
    'Vietnam': 'vi',
    'Vanuatu': 'bi, en, fr',
    'Wallis and Futuna': 'fr',
    'Samoa': 'sm, en',
    'Yemen': 'ar',
    'Mayotte': 'fr',
    'South Africa': 'en, af, st, tn, xh, zu',
    'Zambia': 'en',
    'Zimbabwe': 'en, sn, nd',
}
